spring:
  datasource.url: jdbc:mysql://localhost:3306/gestionStock?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
  datasource.username : root
  jpa.show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL

server:
  port: 0001
